---
# Starter pipeline Start with a minimal pipeline that you can customize
# to build and deploy your code.  Add steps that build, run tests,
# deploy, and more: https://aka.ms/yaml

trigger:
  - master
  - azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  imageName: '2dii_pacta'

resources:
  repositories:
    - repository: create_interactive_report
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/create_interactive_report
      ref: master
    - repository: r2dii.climate.stress.test
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/r2dii.climate.stress.test
      ref: master
    - repository: r2dii.stress.test.data
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/r2dii.stress.test.data
      ref: master
    - repository: pacta-data
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/pacta-data
      ref: master

stages:
  - stage: build_image
    displayName: Build Docker Image
    jobs:
      - job: Build
        displayName: Checkout Repos & Build
        steps:
          - checkout: self  # PACTA_analysis repo
            path: repos/PACTA_analysis
          - checkout: create_interactive_report
            path: repos/create_interactive_report
          - checkout: r2dii.climate.stress.test
            path: repos/r2dii.climate.stress.test
          - checkout: r2dii.stress.test.data
            path: repos/r2dii.stress.test.data
          - checkout: pacta-data
            path: repos/pacta-data
          - script: ls -lR $(Agent.BuildDirectory)
          # TODO: Add Tagging steps
          - task: Docker@2
            displayName: Build Transition Monitor Docker image
            inputs:
              repository: $(imageName)
              command: build
              Dockerfile: $(Agent.BuildDirectory)/repos/PACTA_analysis/transitionmonitor_docker/Dockerfile
              buildContext: repos
