---
# Starter pipeline Start with a minimal pipeline that you can customize
# to build and deploy your code.  Add steps that build, run tests,
# deploy, and more: https://aka.ms/yaml

trigger:
  - master
  - azure-pipelines

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: create_interactive_report
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/create_interactive_report
      ref: master
    - repository: r2dii.climate.stress.test
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/r2dii.climate.stress.test
      ref: master
    - repository: r2dii.stress.test.data
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/r2dii.stress.test.data
      ref: master
    - repository: pacta-data
      type: github
      endpoint: 2DegreesInvesting  # Servce connection name
      name: 2DegreesInvesting/pacta-data
      ref: master

stages:
  - stage: build_image
    displayName: Build Docker Image
    jobs:
      - job: checkout_repos
        displayName: Checkout Repos
        steps:
          - checkout: create_interactive_report
          - checkout: r2dii.climate.stress.test
          - checkout: r2dii.stress.test.data
          - checkout: pacta-data
          - script: ls -lR $(Agent.BuildDirectory)
      # - job: list_repos
      #   displayName: List Repos
      #   dependsOn: checkout_repos  # checkout first
      #   steps:
      #     - script: ls -lR $(Agent.BuildDirectory)
      #       # Each job runs on one agent. A job can also be agentless.
      #       # https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops
