---
# Starter pipeline Start with a minimal pipeline that you can customize
# to build and deploy your code.  Add steps that build, run tests,
# deploy, and more: https://aka.ms/yaml
# r2dii.climate.stress.test r2dii.stress.test.data pacta-data

trigger:
  - master
  - azure-pipelines

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: create_interactive_report
    type: github
    endpoint: 2DegreesInvesting
    name: 2DegreesInvesting/create_interactive_report

stages:
- stage: checkout_repos
  displayName: Checkout Repos
  jobs:
  - job: Build_api
    displayName: Build API
    steps:
    - checkout: create_interactive_report
