name: 'Checkout PACTA siblings'
description: 'Checkout PACTA_analysis and the sibling repositories it depends on'
runs:
  using: "composite"
  steps:

    - name: Checkout PACTA_analysis
      uses: actions/checkout@v2
      with:
        repository: 2DegreesInvesting/PACTA_analysis
        path: PACTA_analysis

    - name: Checkout pacta-data
      uses: actions/checkout@v2
      with:
        repository: 2DegreesInvesting/pacta-data
        token: ${{ secrets.MAURO_PAT_FOR_2DII }}
        path: pacta-data

    - name: Checkout create_interactive_report
      uses: actions/checkout@v2
      with:
        repository: 2DegreesInvesting/create_interactive_report
        token: ${{ secrets.MAURO_PAT_FOR_2DII }}
        path: create_interactive_report

    - name: Checkout StressTestingModelDev
      uses: actions/checkout@v2
      with:
        repository: 2DegreesInvesting/StressTestingModelDev
        token: ${{ secrets.MAURO_PAT_FOR_2DII }}
        path: StressTestingModelDev

    - name: Checkout user_results
      uses: actions/checkout@v2
      with:
        repository: 2DegreesInvesting/user_results
        token: ${{ secrets.MAURO_PAT_FOR_2DII }}
        path: user_results
