on: [push, pull_request]

name: Render reprex

jobs:
  render:
    name: Render reprex.Rmd
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: |
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render reprex.Rmd
        run: Rscript -e 'rmarkdown::render("reprex.Rmd")'

