on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: 2dii/r-packages
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/create_interactive_report
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
      - uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/StressTestingModelDev
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
      - uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/pacta-data
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
      - uses: actions/checkout@v2
      - run: ls -al
      - run: ls -al ../
      - run: ./bin/run-web-tool
