on: [push, pull_request]

name: Test R scripts on 2dii runners

jobs:
  Test-r-scripts:
    runs-on: ${{ matrix.config.os }}
    container:
      image: 2dii/r-packages:latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          # Container operations are only supported on Linux runners
          - {os: ubuntu-16.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest", http-user-agent: "R/4.0.0 (ubuntu-16.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
          - {os: ubuntu-16.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: '3.5',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout PACTA_analysis
        uses: actions/checkout@v2
        with:
          path: PACTA_analysis
      - name: Checkout pacta-data
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/pacta-data
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: pacta-data
      - name: Checkout create_interactive_report
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/create_interactive_report
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: create_interactive_report
      - name: Checkout StressTestingModelDev
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/StressTestingModelDev
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: StressTestingModelDev
      - name: Checkout user_results
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/user_results
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: user_results

      - name: Test R scripts
        run: |
          setwd("PACTA_analysis")
          source("R/test_r_scripts.R")
          test_r_scripts()
        shell: Rscript {0}




