name: Run web tool scripts on custom docker

on: [push, pull_request]

jobs:
  setup_docker_host:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout PACTA_analysis
        uses: actions/checkout@v2
        with:
          path: PACTA_analysis
      - name: Checkout pacta-data
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/pacta-data
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: pacta-data
      - name: Checkout create_interactive_report
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/create_interactive_report
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: create_interactive_report
      - name: Checkout StressTestingModelDev
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/StressTestingModelDev
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: StressTestingModelDev
      - name: Checkout user_results
        uses: actions/checkout@v2
        with:
          repository: 2DegreesInvesting/user_results
          token: ${{ secrets.MAURO_PAT_FOR_2DII }}
          path: user_results
  setup_docker_instance:
    runs-on: ubuntu-18.04
    container:
      image: 2dii/r-packages
      volumes:
        - PACTA_analysis:/bound
        - pacta-data:/pacta-data
        - create_interactive_report:/create_interactive_report
        - StressTestingModelDev:/StressTestingModelDev
        - user_results:/user_results
    steps:
      - name: cd to working directory
        run: cd /bound
      - name: list files in root directory
        run: ls -al /
      - name: list files in bound directory
        run: ls -al /bound
      - name: list files in bound bin directory
        run: ls -al /bound/bin
      - name: list files in working directory
        run: ls -al
      - name: list files in bin directory
        run: ls -al bin
      - name: run web tool scripts
        run: ./bin/run-web-tool
